name: Deploy Eleventy Site to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment when pushing to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from GitHub
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Specify the Node.js version you're using

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci  # Use npm ci for clean install (or npm install if you prefer)

      # Step 4: Build the Eleventy site
      - name: Build with Eleventy
        run: npx @11ty/eleventy  # Build the Eleventy site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code again (for deployment)
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # The branch to deploy to (typically gh-pages)
          folder: _site     # The folder containing the Eleventy build output
